DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlbzAwZ21AZ21haWwuY29tIiwiZXhwIjoxNzI1ODAyODAxLCJ1c2VySWQiOjJ9.jXZbiX0slslsWMTSsl9G8lTl4HZ7yw8beTui66KxH9I