POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdHRlbzAwZ21AZ21haWwuY29tIiwiZXhwIjoxNzI1ODAyMzIzLCJ1c2VySWQiOjJ9.cmND9ivguQ3YMzMfrNUeSPyJaJqfeBvN4N0HkpbnJOM